(let* ((n (read))
       (m (read))
       (u (read))
       (an (loop repeat (1- n) collect (read)))
       (xym (loop repeat m collect (cons (read) (read)))))
  (loop for a in an for i from 1 with xy = (and xym (pop xym))
        when (and xy (= (car xy) i))
          do (incf u (cdr xy))
          and when xym
                do (setf xy (pop xym))
        do (decf u a)
        when (<= u 0)
          return (princ "No")
        finally (princ "Yes")))
