(let* ((n (read))
       (s (make-array n :initial-contents (read-line)))
       (u (make-array n :initial-contents (read-line))))
  (format t "~:[No~;Yes~]" (every #'(lambda (x y) (or (char= x y)
                                                      (and (or (char= x #\1)
                                                               (char= x #\l))
                                                           (or (char= y #\1)
                                                               (char= y #\l)))
                                                      (and (or (char= x #\0)
                                                               (char= x #\o))
                                                           (or (char= y #\0)
                                                               (char= y #\o)))))
                                  s u)))
