(let* ((xa (read)) (ya (read))
       (xb (read)) (yb (read))
       (xc (read)) (yc (read))
       (dab2 (+ (expt (- xb xa) 2) (expt (- yb ya) 2)))
       (dbc2 (+ (expt (- xc xb) 2) (expt (- yc yb) 2)))
       (dca2 (+ (expt (- xa xc) 2) (expt (- ya yc) 2))))
  (format t "~:[No~;Yes~]" (or (= dab2 (+ dbc2 dca2))
                               (= dbc2 (+ dab2 dca2))
                               (= dca2 (+ dab2 dbc2)))))
