(let ((l (read))
      (r (read)))
  (cond ((= l r 1)
         (princ "Invalid"))
        ((= l r 0)
         (princ "Invalid"))
        ((= l 1)
         (princ "Yes"))
        ((= r 1)
         (princ "No"))))
