(let* ((n (read))
       (m (read))
       (abm (loop repeat m collect (cons (read) (read-char)))))
  (loop for (a . b) in abm with hash = (make-hash-table)
        do (when (char= b #\M)
             (incf (gethash a hash 0)))
           (if (and (= (gethash a hash 0) 1) (char= b #\M))
               (format t "Yes~%")
               (format t "No~%"))))
