(let* ((a (read)) (b (read)) (c (read)) (d (read)) (e (read)) (f (read))
       (g (read)) (h (read)) (i (read)) (j (read)) (k (read)) (l (read))
       (amaxx (max a d)) (amaxy (max b e)) (amaxz (max c f))
       (bmaxx (max g j)) (bmaxy (max h k)) (bmaxz (max i l))
       (aminx (min a d)) (aminy (min b e)) (aminz (min c f))
       (bminx (min g j)) (bminy (min h k)) (bminz (min i l)))
  (format t "~:[No~;Yes~]" (and (< aminx bmaxx) (< bminx amaxx)
                                (< aminy bmaxy) (< bminy amaxy)
                                (< aminz bmaxz) (< bminz amaxz))))
