(let* ((n (read))
       (k (read))
       (an (loop repeat n collect (read)))
       (bn (coerce (sort an #'<) 'vector)))
    (loop repeat k
          do (let ((e0 (elt bn (- (length bn) 1)))
                   (e1 (elt bn (- (length bn) 2)))
                   (s0 (elt bn 0))
                   (s1 (elt bn 1)))
               (if (< (- e1 s0) (- e0 s1))
                   (setf bn (remove e0 bn :count 1 :from-end t)))
                   (setf bn (remove s0 bn :count 1)))
          finally (let ((bn (coerce bn 'list)))
                    (print (- (apply #'max bn) (apply #'min bn))))))
