(let* ((n (read))
       (s (read-line))
       (ct (count #\T s))
       (ca (count #\A s))
       (pt (position #\T s :from-end t))
       (pa (position #\A s :from-end t)))
  (cond ((< ca ct)
         (princ "T"))
        ((< ct ca)
         (princ "A"))
        (t
         (if (< pa pt)
             (princ "A")
             (princ "T")))))
