(let ((mn (read))
      (dn (read))
      (y (read))
      (m (read))
      (d (read)))
  (let* ((dt (1+ (mod d dn)))
         (mt (if (= dt 1) (1+ (mod m mn)) m))
         (yt (if (= dt mt 1) (1+ y) y)))
    (format t "~a ~a ~a" yt mt dt)))
