(destructuring-bind (a b c d e f x) (loop repeat 7 collect (read))
  (flet ((dist (a b c x)
           (let ((cycle (floor x (+ a c)))
                 (last (min (mod x (+ a c)) a)))
             (* (+ (* cycle a) last) b))))
    (let ((takahashi (dist a b c x))
          (aoki (dist d e f x)))
      (cond ((= takahashi aoki) (princ "Draw"))
            ((< takahashi aoki) (princ "Aoki"))
            (t (princ "Takahashi"))))))
