(let* ((n (read))
       (m (read))
       (abm (loop repeat m collect (list (1- (read)) (1- (read))))))
  (loop for (nil b) in abm with loser = (make-array n :initial-element nil)
        do (setf (elt loser b) t)
        finally (print (if (= (count nil loser) 1)
                           (1+ (position nil loser))
                           -1))))
