(let* ((n (read))
       (m (read))
       (an (loop repeat n collect (read)))
       (bm (loop repeat m collect (read))))
  (loop for b in bm with pasta = (make-hash-table)
          initially (loop for a in an do (incf (gethash a pasta 0)))
        when (minusp (decf (gethash b pasta 0)))
          return (princ "No")
        finally (princ "Yes")))
