(let* ((n (read))
       (k (read))
       (rn (loop repeat n collect (read))))
  (labels ((recursion (lst)
             (if (= (length lst) n)
                 (when (zerop (mod (reduce #'+ lst) k))
                   (format t "~{~a ~}~%" (reverse lst)))
                 (loop for i from 1 to (elt rn (length lst))
                       do (recursion (cons i lst))))))
    (recursion nil)))
