(let* ((w (read))
       (b (read))
       (s "wbwbwwbwbwbw")
       (piano (loop repeat (1+ (ceiling (+ w b) (length s)) ) with str
                    do (setf str (concatenate 'string str s))
                    finally (return str))))
  (loop for i from 0 until (= (+ i w b) (length piano))
        do (let ((str (subseq piano i (+ i w b))))
             (when (and (= (count #\w str) w)
                        (= (count #\b str) b))
               (return (princ "Yes"))))
        finally (princ "No")))
