(let ((s (read-line)))
  (format t "~a" (if (and (string= (subseq s 0 1) "<")
                          (= (count #\< s) 1)
                          (string= (subseq s (1- (length s))) ">")
                          (= (count #\> s) 1))
                     "Yes" "No")))
