(let* ((n (read))
       (q (read))
       (qq (loop repeat q collect (list (read) (read))))
       (loong (make-array (expt 10 6) :fill-pointer 0 :adjustable t)))
  (loop for i from n downto 1 do (vector-push (list i 0) loong))
  (flet ((head (loong)
           (elt loong (1- (length loong)))))
    (loop for (com cp) in qq
          with dir = '((R 1 0) (L -1 0) (U 0 1) (D 0 -1))
          do (if (= com 1)
                 (vector-push-extend
                  (list (+ (elt (assoc cp dir) 1) (elt (head loong) 0))
                        (+ (elt (assoc cp dir) 2) (elt (head loong) 1)))
                  loong)
                 (format t "~{~a ~a~}~%" (elt loong (- (length loong) cp)))))))
