(let* ((n (read))
       (an (loop repeat n collect (read)))
       (par (make-array (* 2 (1+ n)) :initial-element 0))
       (gen (make-array (* 2 (1+ n)) :initial-element 0)))
  (loop for i from 1 for a in an
        do (setf (elt par (* 2 i)) a)
           (setf (elt par (1+ (* 2 i))) a))
  (loop for i from 2 below (* 2 (1+ n))
        do (setf (elt gen i) (1+ (elt gen (elt par i)))))
  (loop for i from 1 below (* 2 (1+ n))
        do (format t "~a~%" (elt gen i))))
